# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Charpter',
        ),
    ]
