# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'items'},
        ),
    ]
