# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20171008_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='charpterEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'charpterentries',
            },
        ),
        migrations.CreateModel(
            name='itemEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'itementries',
            },
        ),
        migrations.RemoveField(
            model_name='charpter',
            name='body',
        ),
        migrations.RemoveField(
            model_name='item',
            name='body',
        ),
        migrations.AddField(
            model_name='itementry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Item'),
        ),
        migrations.AddField(
            model_name='charpterentry',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Charpter'),
        ),
    ]
