# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20171008_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charpter',
            options={},
        ),
        migrations.AlterField(
            model_name='charpter',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='charpterentry',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
