# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20171008_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charpter',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterField(
            model_name='charpter',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='charpterentry',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
