# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20171009_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
